package completion

import (
	"fmt"
	"strings"
)

// Bash renders a bash-completion script.
//
// The shape is the one bash-completion expects: one function, registered with
// `complete -F`. Two things in it are worth knowing. Value completion is decided
// from the *previous word* alone, with no idea which subcommand it sits in —
// hence Validate's cross-command check. And the flag list offered before any
// subcommand is the default command's, because `drivel -mount ...` means
// `drivel mount -mount ...`; offering the union of every command's flags there
// would suggest flags that the line, once completed, cannot accept.
func Bash(a App) ([]byte, error) {
	if err := a.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("# bash completion for %s                               -*- shell-script -*-", a.Name)
	p("#")
	p("# GENERATED by `%s completion bash` from the flag definitions in cmd/%s.", a.Name, a.Name)
	p("# Do not edit: add the flag, give it a completion hint, and regenerate.")
	p("#")
	p("# Use it in this shell:")
	p("#   eval \"$(%s completion bash)\"", a.Name)
	p("#")
	p("# Install it permanently:")
	p("#   # per-user:")
	p("#   %s completion bash > ~/.local/share/bash-completion/completions/%s", a.Name, a.Name)
	p("#   # system-wide:")
	p("#   %s completion bash | sudo tee /usr/share/bash-completion/completions/%s >/dev/null", a.Name, a.Name)
	p("#")
	p("# Requires the bash-completion package for the _init_completion helper; a")
	p("# minimal fallback is used when it is absent.")
	p("")
	p("_%s() {", a.Name)
	p("    local cur prev words cword")
	p("    if declare -F _init_completion >/dev/null 2>&1; then")
	p("        _init_completion -n : || return")
	p("    else")
	p("        # Minimal fallback when bash-completion isn't loaded.")
	p("        COMPREPLY=()")
	p(`        cur="${COMP_WORDS[COMP_CWORD]}"`)
	p(`        prev="${COMP_WORDS[COMP_CWORD-1]}"`)
	p(`        words=("${COMP_WORDS[@]}")`)
	p("        cword=$COMP_CWORD")
	p("    fi")
	p("")
	p(`    local subcommands="%s"`, joinWords(a.commandNames()))
	p("")
	p("    # Determine the active subcommand (first non-flag word after the program).")
	p(`    local sub="" i`)
	p("    for (( i=1; i < cword; i++ )); do")
	p(`        case "${words[i]}" in`)
	p("            -*) ;;")
	p(`            *) sub="${words[i]}"; break ;;`)
	p("        esac")
	p("    done")
	if def, ok := a.defaultCommand(); ok {
		p("    # A leading flag (e.g. `%s -%s ...`) implies the default command.",
			a.Name, firstFlagName(def))
		p(`    if [[ -z $sub && ${words[1]} == -* ]]; then`)
		p(`        sub="%s"`, def.Name)
		p("    fi")
	}
	p("")
	p("    # Value completion, decided by the flag before the cursor.")
	p(`    case "$prev" in`)
	if dirs := a.flagsByKind(Dir); len(dirs) > 0 {
		p("        %s)", strings.Join(dirs, "|"))
		p("            _filedir -d")
		p("            return")
		p("            ;;")
	}
	if files := a.flagsByKind(File); len(files) > 0 {
		p("        %s)", strings.Join(files, "|"))
		p("            _filedir")
		p("            return")
		p("            ;;")
	}
	for _, f := range a.enumFlags() {
		p("        -%s)", f.Name)
		p(`            COMPREPLY=( $(compgen -W "%s" -- "$cur") )`, joinWords(f.Values))
		p("            return")
		p("            ;;")
	}
	if opaque := a.flagsByKind(Opaque); len(opaque) > 0 {
		p("        %s)", strings.Join(opaque, "|"))
		p("            # Values nothing can suggest: an ID, a port, a duration.")
		p("            return")
		p("            ;;")
	}
	p("    esac")
	p("")
	p("    # The command slot: a subcommand, or the default command's flags.")
	p("    if [[ -z $sub ]]; then")
	p("        if [[ $cur == -* ]]; then")
	if def, ok := a.defaultCommand(); ok {
		p(`            COMPREPLY=( $(compgen -W "%s" -- "$cur") )`, joinWords(flagNames(def)))
	} else {
		p("            return")
	}
	p("        else")
	p(`            COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )`)
	p("        fi")
	p("        return")
	p("    fi")
	p("")
	p("    # Flag completion within a subcommand.")
	p(`    local flags=""`)
	p(`    case "$sub" in`)
	for _, c := range a.Commands {
		p(`        %s) flags="%s" ;;`, c.Name, joinWords(flagNames(c)))
	}
	for _, c := range a.Extra {
		p("        %s) return ;;", c.Name)
	}
	p("    esac")
	p("    if [[ $cur == -* ]]; then")
	p(`        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )`)
	p("    fi")
	p("}")
	p("")
	p("complete -F _%s %s", a.Name, a.Name)
	return []byte(b.String()), nil
}

// firstFlagName is only ever used to write a plausible example in a comment.
func firstFlagName(c Command) string {
	for _, f := range c.Flags {
		if f.Kind != None {
			return f.Name
		}
	}
	return "flag"
}
