// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0

package completion

import (
	"fmt"
	"strings"
)

// Zsh renders a zsh completion function, in the `#compdef` form that goes into a
// directory on $fpath.
//
// Unlike bash, zsh completes per subcommand, so each command gets its own
// _arguments call and the cross-command constraint does not apply here. What
// does apply is quoting: a description sits inside `[...]` in a single-quoted
// word, and an unescaped bracket, colon or quote in it produces a file that
// fails to load rather than one that completes badly. See quoteZsh.
func Zsh(a App) ([]byte, error) {
	if err := a.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("#compdef %s", a.Name)
	p("# zsh completion for %s", a.Name)
	p("#")
	p("# GENERATED by `%s completion zsh` from the flag definitions in cmd/%s.", a.Name, a.Name)
	p("# Do not edit: add the flag, give it a completion hint, and regenerate.")
	p("#")
	p("# Install: write this to a file named `_%s` in a directory on your $fpath,", a.Name)
	p("# then restart zsh or run `compinit`. For example:")
	p("#")
	p("#   mkdir -p ~/.zsh/completions")
	p("#   %s completion zsh > ~/.zsh/completions/_%s", a.Name, a.Name)
	p("#   # in ~/.zshrc, before `compinit`:")
	p("#   fpath=(~/.zsh/completions $fpath)")
	p("#   autoload -Uz compinit && compinit")
	p("#")
	p("# The eval form works too, but only *after* compinit has run, because that is")
	p("# what defines compdef, which is how this file registers itself when it is not")
	p("# being autoloaded:")
	p("#   autoload -Uz compinit && compinit")
	p("#   eval \"$(%s completion zsh)\"", a.Name)
	p("")
	p("_%s() {", a.Name)
	p(`    local curcontext="$curcontext" state line`)
	p("    typeset -A opt_args")
	p("")
	p("    local -a subcommands")
	p("    subcommands=(")
	for _, c := range append(append([]Command{}, a.Commands...), a.Extra...) {
		p("        '%s:%s'", c.Name, quoteZsh(c.Summary))
	}
	p("    )")
	p("")
	def, hasDefault := a.defaultCommand()
	p("    # The first argument may be a subcommand, or a flag.")
	p("    _arguments -C \\")
	p("        '1: :->command' \\")
	p("        '*:: :->args' && return 0")
	p("")
	p("    case $state in")
	p("        command)")
	p("            if [[ $words[CURRENT] == -* ]]; then")
	if hasDefault {
		p("                _%s_%s_args   # a leading flag implies the default command", a.Name, def.Name)
	} else {
		p("                return 1")
	}
	p("            else")
	p("                _describe -t commands '%s command' subcommands", a.Name)
	p("            fi")
	p("            ;;")
	p("        args)")
	p("            case $line[1] in")
	for _, c := range a.Commands {
		p("                %s) _%s_%s_args ;;", c.Name, a.Name, c.Name)
	}
	if hasDefault {
		p("                *)     _%s_%s_args ;;", a.Name, def.Name)
	}
	p("            esac")
	p("            ;;")
	p("    esac")
	p("}")

	for _, c := range a.Commands {
		p("")
		p("_%s_%s_args() {", a.Name, c.Name)
		p("    _arguments -s \\")
		for _, f := range c.Flags {
			p("        %s \\", zshFlag(f))
		}
		p("        '(-h -help)'{-h,-help}'[show %s usage]'", c.Name)
		p("}")
	}
	p("")
	// How this file is reached decides what the last line must do, and it cannot
	// be told at render time. Autoloaded from $fpath the whole file *is* the body
	// of _NAME, so it has to end by calling the function it just defined;
	// eval'd or sourced, nothing has registered the function with the completion
	// system and calling it runs _arguments outside a completion widget, which
	// fails with "can only be called from completion function". $funcstack is what
	// distinguishes them: it names _NAME only in the autoload case.
	p("if [[ $funcstack[1] == _%s ]]; then", a.Name)
	p(`    _%s "$@"`, a.Name)
	p("elif (( $+functions[compdef] )); then")
	p("    compdef _%s %s", a.Name, a.Name)
	p("else")
	p(`    print -u2 -- '_%s: run compinit before eval "$(%s completion zsh)"'`, a.Name, a.Name)
	// false and not `return 1`: this is most often eval'd from .zshrc, where a
	// return inside an eval returns from the sourced file and silently abandons
	// the rest of someone's shell configuration. A non-zero status is worth
	// reporting; taking the rest of .zshrc with it is not.
	p("    false")
	p("fi")
	return []byte(b.String()), nil
}

// zshFlag is one _arguments spec: the flag, its description, and what its value
// completes to.
func zshFlag(f Flag) string {
	desc := "[" + quoteZsh(f.Summary) + "]"
	arg := f.Arg
	if arg == "" {
		arg = f.Name
	}
	arg = quoteZsh(arg)
	switch f.Kind {
	case None:
		return "'-" + f.Name + desc + "'"
	case File:
		return "'-" + f.Name + "=" + desc + ":" + arg + ":_files'"
	case Dir:
		return "'-" + f.Name + "=" + desc + ":" + arg + ":_files -/'"
	case Enum:
		return "'-" + f.Name + "=" + desc + ":" + arg + ":(" + joinWords(f.Values) + ")'"
	default: // Opaque
		return "'-" + f.Name + "=" + desc + ":" + arg + ":'"
	}
}

// quoteZsh makes a description safe inside a single-quoted _arguments word.
//
// Four characters matter and each breaks something different: a single quote
// ends the word, a colon starts the next _arguments field, a bracket closes the
// description early, and a backslash escapes whatever follows it. Getting this
// wrong yields a completion file that fails to load — which is why the summaries
// are checked here rather than trusted to whoever wrote them.
func quoteZsh(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`'`, `'\''`,
		`:`, `\:`,
		`[`, `\[`,
		`]`, `\]`,
	)
	return r.Replace(s)
}
