package completion

import (
	"fmt"
	"strings"
)

// Zsh renders a zsh completion function, in the `#compdef` form that goes into a
// directory on $fpath.
//
// Unlike bash, zsh completes per subcommand, so each command gets its own
// _arguments call and the cross-command constraint does not apply here. What
// does apply is quoting: a description sits inside `[...]` in a single-quoted
// word, and an unescaped bracket, colon or quote in it produces a file that
// fails to load rather than one that completes badly. See quoteZsh.
func Zsh(a App) ([]byte, error) {
	if err := a.Validate(); err != nil {
		return nil, err
	}
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("#compdef %s", a.Name)
	p("# zsh completion for %s", a.Name)
	p("#")
	p("# GENERATED by `make completions` from the flag definitions in cmd/%s.", a.Name)
	p("# Do not edit: add the flag, give it a completion hint, and regenerate.")
	p("#")
	p("# Install: place this file (named `_%s`) in a directory on your $fpath,", a.Name)
	p("# then restart zsh or run `compinit`. For example:")
	p("#")
	p("#   mkdir -p ~/.zsh/completions")
	p("#   cp completions/_%s ~/.zsh/completions/_%s", a.Name, a.Name)
	p("#   # in ~/.zshrc, before `compinit`:")
	p("#   fpath=(~/.zsh/completions $fpath)")
	p("#   autoload -Uz compinit && compinit")
	p("")
	p("_%s() {", a.Name)
	p(`    local curcontext="$curcontext" state line`)
	p("    typeset -A opt_args")
	p("")
	p("    local -a subcommands")
	p("    subcommands=(")
	for _, c := range append(append([]Command{}, a.Commands...), a.Extra...) {
		p("        '%s:%s'", c.Name, quoteZsh(c.Summary))
	}
	p("    )")
	p("")
	def, hasDefault := a.defaultCommand()
	p("    # The first argument may be a subcommand, or a flag.")
	p("    _arguments -C \\")
	p("        '1: :->command' \\")
	p("        '*:: :->args' && return 0")
	p("")
	p("    case $state in")
	p("        command)")
	p("            if [[ $words[CURRENT] == -* ]]; then")
	if hasDefault {
		p("                _%s_%s_args   # a leading flag implies the default command", a.Name, def.Name)
	} else {
		p("                return 1")
	}
	p("            else")
	p("                _describe -t commands '%s command' subcommands", a.Name)
	p("            fi")
	p("            ;;")
	p("        args)")
	p("            case $line[1] in")
	for _, c := range a.Commands {
		p("                %s) _%s_%s_args ;;", c.Name, a.Name, c.Name)
	}
	if hasDefault {
		p("                *)     _%s_%s_args ;;", a.Name, def.Name)
	}
	p("            esac")
	p("            ;;")
	p("    esac")
	p("}")

	for _, c := range a.Commands {
		p("")
		p("_%s_%s_args() {", a.Name, c.Name)
		p("    _arguments -s \\")
		for _, f := range c.Flags {
			p("        %s \\", zshFlag(f))
		}
		p("        '(-h -help)'{-h,-help}'[show %s usage]'", c.Name)
		p("}")
	}
	p("")
	p(`_%s "$@"`, a.Name)
	return []byte(b.String()), nil
}

// zshFlag is one _arguments spec: the flag, its description, and what its value
// completes to.
func zshFlag(f Flag) string {
	desc := "[" + quoteZsh(f.Summary) + "]"
	arg := f.Arg
	if arg == "" {
		arg = f.Name
	}
	arg = quoteZsh(arg)
	switch f.Kind {
	case None:
		return "'-" + f.Name + desc + "'"
	case File:
		return "'-" + f.Name + "=" + desc + ":" + arg + ":_files'"
	case Dir:
		return "'-" + f.Name + "=" + desc + ":" + arg + ":_files -/'"
	case Enum:
		return "'-" + f.Name + "=" + desc + ":" + arg + ":(" + joinWords(f.Values) + ")'"
	default: // Opaque
		return "'-" + f.Name + "=" + desc + ":" + arg + ":'"
	}
}

// quoteZsh makes a description safe inside a single-quoted _arguments word.
//
// Four characters matter and each breaks something different: a single quote
// ends the word, a colon starts the next _arguments field, a bracket closes the
// description early, and a backslash escapes whatever follows it. Getting this
// wrong yields a completion file that fails to load — which is why the summaries
// are checked here rather than trusted to whoever wrote them.
func quoteZsh(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`'`, `'\''`,
		`:`, `\:`,
		`[`, `\[`,
		`]`, `\]`,
	)
	return r.Replace(s)
}
