// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0

// The drivel provider plugin protocol (M9).
//
// This file is the compatibility surface between a drivel host and a backend
// running in its own process. Everything in it mirrors a Go declaration in
// github.com/zishmusic/drivel/provider, and the mapping is deliberately dull:
// the seam was designed in M2 and proven in M8, and M9 is about the loading
// mechanism, not about redesigning the interface.
//
// Two rules govern changes here.
//
//   - Fields are added, never renumbered or reused. A host and a plugin are
//     separately built binaries that a user may upgrade independently, which is
//     the whole reason the protocol exists.
//   - A capability is named by a string, not by a field number. Which optional
//     interfaces a backend offers is answered once, at Open, because a gRPC stub
//     implements every method whether or not the backend behind it can honour
//     them — see provider.Capability for what goes wrong otherwise.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: drivel/plugin/v1/provider.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error_Kind int32

const (
	Error_KIND_UNSPECIFIED    Error_Kind = 0
	Error_KIND_NOT_EXIST      Error_Kind = 1 // provider.ErrNotExist
	Error_KIND_CURSOR_EXPIRED Error_Kind = 2 // provider.ErrCursorExpired
)

// Enum value maps for Error_Kind.
var (
	Error_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_NOT_EXIST",
		2: "KIND_CURSOR_EXPIRED",
	}
	Error_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":    0,
		"KIND_NOT_EXIST":      1,
		"KIND_CURSOR_EXPIRED": 2,
	}
)

func (x Error_Kind) Enum() *Error_Kind {
	p := new(Error_Kind)
	*p = x
	return p
}

func (x Error_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_drivel_plugin_v1_provider_proto_enumTypes[0].Descriptor()
}

func (Error_Kind) Type() protoreflect.EnumType {
	return &file_drivel_plugin_v1_provider_proto_enumTypes[0]
}

func (x Error_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error_Kind.Descriptor instead.
func (Error_Kind) EnumDescriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{28, 0}
}

type OpenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// config is the provider's own settings as TOML text — the same bytes
	// provider.Config carries in process. The host does not parse them.
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// content_broker_id names the Content service the host serves for the life of
	// this connection. The plugin dials it the first time it needs to read a local
	// file back, and keeps the connection; a backend that never patches extents
	// never dials at all.
	//
	// It is established once here rather than per call because go-plugin's
	// AcceptAndServe runs until the whole broker shuts down, so a listener per
	// PutRange would be a listener per PutRange for the life of the mount.
	ContentBrokerId uint32 `protobuf:"varint,2,opt,name=content_broker_id,json=contentBrokerId,proto3" json:"content_broker_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *OpenRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *OpenRequest) GetContentBrokerId() uint32 {
	if x != nil {
		return x.ContentBrokerId
	}
	return 0
}

type OpenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// capabilities names the optional interfaces this backend offers, using the
	// wire names in provider.Capability. A name the host does not recognise is
	// ignored, so a newer plugin talking to an older host loses that capability
	// rather than the connection.
	Capabilities  []string `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *OpenResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{2}
}

type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{3}
}

// File is provider.RemoteFile.
type File struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IsDir   bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size    int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Hash    string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Version string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// modified is unset for the zero time, which is what a backend that does not
	// report modification times leaves it as. A Unix epoch field could not tell
	// "1970" from "not reported", and the sweep's mtime comparisons read the
	// difference.
	Modified      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified,proto3" json:"modified,omitempty"`
	ExportOnly    bool                   `protobuf:"varint,7,opt,name=export_only,json=exportOnly,proto3" json:"export_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *File) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *File) GetModified() *timestamppb.Timestamp {
	if x != nil {
		return x.Modified
	}
	return nil
}

func (x *File) GetExportOnly() bool {
	if x != nil {
		return x.ExportOnly
	}
	return false
}

// Change is provider.RemoteChange.
type Change struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	File          *File                  `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"` // unset when removed is true
	Removed       bool                   `protobuf:"varint,3,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Change) Reset() {
	*x = Change{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Change) ProtoMessage() {}

func (x *Change) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Change.ProtoReflect.Descriptor instead.
func (*Change) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *Change) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Change) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *Change) GetRemoved() bool {
	if x != nil {
		return x.Removed
	}
	return false
}

// Chunk is a run of bytes in a stream.
type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PutRequest_Path
	//	*PutRequest_Data
	Msg           isPutRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *PutRequest) GetMsg() isPutRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PutRequest) GetPath() string {
	if x != nil {
		if x, ok := x.Msg.(*PutRequest_Path); ok {
			return x.Path
		}
	}
	return ""
}

func (x *PutRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*PutRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isPutRequest_Msg interface {
	isPutRequest_Msg()
}

type PutRequest_Path struct {
	Path string `protobuf:"bytes,1,opt,name=path,proto3,oneof"` // exactly once, first
}

type PutRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"` // zero or more, after
}

func (*PutRequest_Path) isPutRequest_Msg() {}

func (*PutRequest_Data) isPutRequest_Msg() {}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *FileResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type MoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *MoveRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *MoveRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{12}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *GetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	File  *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// ok distinguishes "no such object" from an error. Stat is the one call in the
	// seam where absence is an ordinary answer, so it must not arrive as a status
	// code that a retry loop might read as a failure.
	Ok            bool `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *StatResponse) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *StatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StartCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCursorRequest) Reset() {
	*x = StartCursorRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCursorRequest) ProtoMessage() {}

func (x *StartCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCursorRequest.ProtoReflect.Descriptor instead.
func (*StartCursorRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{16}
}

type StartCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCursorResponse) Reset() {
	*x = StartCursorResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCursorResponse) ProtoMessage() {}

func (x *StartCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCursorResponse.ProtoReflect.Descriptor instead.
func (*StartCursorResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{17}
}

func (x *StartCursorResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangesRequest) Reset() {
	*x = ChangesRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesRequest) ProtoMessage() {}

func (x *ChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangesRequest.ProtoReflect.Descriptor instead.
func (*ChangesRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{18}
}

func (x *ChangesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ChangesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changes       []*Change              `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangesResponse) Reset() {
	*x = ChangesResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangesResponse) ProtoMessage() {}

func (x *ChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangesResponse.ProtoReflect.Descriptor instead.
func (*ChangesResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ChangesResponse) GetChanges() []*Change {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ChangesResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

type EnumerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateRequest) Reset() {
	*x = EnumerateRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateRequest) ProtoMessage() {}

func (x *EnumerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateRequest.ProtoReflect.Descriptor instead.
func (*EnumerateRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{20}
}

func (x *EnumerateRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type EnumerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Files []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	// next is "" when the sweep is complete. An empty files list with next == ""
	// is a complete sweep of an empty tree, which is the shape M7b treats as
	// dangerous — the host, not the protocol, decides what to do about that.
	Next          string `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateResponse) Reset() {
	*x = EnumerateResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateResponse) ProtoMessage() {}

func (x *EnumerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateResponse.ProtoReflect.Descriptor instead.
func (*EnumerateResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{21}
}

func (x *EnumerateResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *EnumerateResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

type GetRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Off           int64                  `protobuf:"varint,2,opt,name=off,proto3" json:"off,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"` // <= 0 means "to end of object"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRangeRequest) Reset() {
	*x = GetRangeRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRangeRequest) ProtoMessage() {}

func (x *GetRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRangeRequest.ProtoReflect.Descriptor instead.
func (*GetRangeRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{22}
}

func (x *GetRangeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetRangeRequest) GetOff() int64 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *GetRangeRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

// Extent is ranges.Range.
type Extent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Off           int64                  `protobuf:"varint,1,opt,name=off,proto3" json:"off,omitempty"`
	Len           int64                  `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extent) Reset() {
	*x = Extent{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extent) ProtoMessage() {}

func (x *Extent) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extent.ProtoReflect.Descriptor instead.
func (*Extent) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{23}
}

func (x *Extent) GetOff() int64 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *Extent) GetLen() int64 {
	if x != nil {
		return x.Len
	}
	return 0
}

type PutRangeRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size    int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Extents []*Extent              `protobuf:"bytes,3,rep,name=extents,proto3" json:"extents,omitempty"`
	// source_handle names the local file the host has made readable for this one
	// call. It is registered immediately before the call and dropped immediately
	// after, so a handle is never valid outside the call that carries it — which
	// is what keeps "the plugin can read a file the host chose" from becoming "the
	// plugin can read files".
	SourceHandle  uint64 `protobuf:"varint,4,opt,name=source_handle,json=sourceHandle,proto3" json:"source_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRangeRequest) Reset() {
	*x = PutRangeRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRangeRequest) ProtoMessage() {}

func (x *PutRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRangeRequest.ProtoReflect.Descriptor instead.
func (*PutRangeRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{24}
}

func (x *PutRangeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PutRangeRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PutRangeRequest) GetExtents() []*Extent {
	if x != nil {
		return x.Extents
	}
	return nil
}

func (x *PutRangeRequest) GetSourceHandle() uint64 {
	if x != nil {
		return x.SourceHandle
	}
	return 0
}

type HashContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashContentResponse) Reset() {
	*x = HashContentResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashContentResponse) ProtoMessage() {}

func (x *HashContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashContentResponse.ProtoReflect.Descriptor instead.
func (*HashContentResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{25}
}

func (x *HashContentResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ReadAtRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Off   int64                  `protobuf:"varint,1,opt,name=off,proto3" json:"off,omitempty"`
	Len   int32                  `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	// handle is the source_handle of the PutRange call being served.
	Handle        uint64 `protobuf:"varint,3,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAtRequest) Reset() {
	*x = ReadAtRequest{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAtRequest) ProtoMessage() {}

func (x *ReadAtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAtRequest.ProtoReflect.Descriptor instead.
func (*ReadAtRequest) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{26}
}

func (x *ReadAtRequest) GetOff() int64 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *ReadAtRequest) GetLen() int32 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *ReadAtRequest) GetHandle() uint64 {
	if x != nil {
		return x.Handle
	}
	return 0
}

type ReadAtResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Data  []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// eof reports that the read stopped at the end of the file, which io.ReaderAt
	// requires be reported alongside a short read rather than as a failure.
	Eof           bool `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAtResponse) Reset() {
	*x = ReadAtResponse{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAtResponse) ProtoMessage() {}

func (x *ReadAtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAtResponse.ProtoReflect.Descriptor instead.
func (*ReadAtResponse) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{27}
}

func (x *ReadAtResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadAtResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

// Error is attached as a gRPC status detail so the sentinels the engine
// switches on survive the process boundary.
//
// Without it every failure would arrive as an opaque string: provider.ErrNotExist
// would stop meaning "upload the destination as fresh content", ErrCursorExpired
// would stop triggering a re-enumeration and inbound sync would silently stop,
// and provider.IsRetryable would report false for every rate limit, turning the
// engine's backoff into a permanent failure on the first 429.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  Error_Kind             `protobuf:"varint,1,opt,name=kind,proto3,enum=drivel.plugin.v1.Error_Kind" json:"kind,omitempty"`
	// retryable is provider.IsRetryable's answer, computed on the plugin side
	// where the backend's own error types are visible.
	Retryable bool `protobuf:"varint,2,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// message is the error's text, for a human reading a log.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_drivel_plugin_v1_provider_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_drivel_plugin_v1_provider_proto_rawDescGZIP(), []int{28}
}

func (x *Error) GetKind() Error_Kind {
	if x != nil {
		return x.Kind
	}
	return Error_KIND_UNSPECIFIED
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_drivel_plugin_v1_provider_proto protoreflect.FileDescriptor

const file_drivel_plugin_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1fdrivel/plugin/v1/provider.proto\x12\x10drivel.plugin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\vOpenRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12*\n" +
	"\x11content_broker_id\x18\x02 \x01(\rR\x0fcontentBrokerId\"2\n" +
	"\fOpenResponse\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"\x0e\n" +
	"\fCloseRequest\"\x0f\n" +
	"\rCloseResponse\"\xcc\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x126\n" +
	"\bmodified\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bmodified\x12\x1f\n" +
	"\vexport_only\x18\a \x01(\bR\n" +
	"exportOnly\"b\n" +
	"\x06Change\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x04file\x18\x02 \x01(\v2\x16.drivel.plugin.v1.FileR\x04file\x12\x18\n" +
	"\aremoved\x18\x03 \x01(\bR\aremoved\"\x1b\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"?\n" +
	"\n" +
	"PutRequest\x12\x14\n" +
	"\x04path\x18\x01 \x01(\tH\x00R\x04path\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\":\n" +
	"\fFileResponse\x12*\n" +
	"\x04file\x18\x01 \x01(\v2\x16.drivel.plugin.v1.FileR\x04file\"\"\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"C\n" +
	"\vMoveRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\x10\n" +
	"\x0eRemoveResponse\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"J\n" +
	"\fStatResponse\x12*\n" +
	"\x04file\x18\x01 \x01(\v2\x16.drivel.plugin.v1.FileR\x04file\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\x14\n" +
	"\x12StartCursorRequest\"-\n" +
	"\x13StartCursorResponse\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"(\n" +
	"\x0eChangesRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"Y\n" +
	"\x0fChangesResponse\x122\n" +
	"\achanges\x18\x01 \x03(\v2\x18.drivel.plugin.v1.ChangeR\achanges\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"*\n" +
	"\x10EnumerateRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"U\n" +
	"\x11EnumerateResponse\x12,\n" +
	"\x05files\x18\x01 \x03(\v2\x16.drivel.plugin.v1.FileR\x05files\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"O\n" +
	"\x0fGetRangeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03off\x18\x02 \x01(\x03R\x03off\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\",\n" +
	"\x06Extent\x12\x10\n" +
	"\x03off\x18\x01 \x01(\x03R\x03off\x12\x10\n" +
	"\x03len\x18\x02 \x01(\x03R\x03len\"\x92\x01\n" +
	"\x0fPutRangeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x122\n" +
	"\aextents\x18\x03 \x03(\v2\x18.drivel.plugin.v1.ExtentR\aextents\x12#\n" +
	"\rsource_handle\x18\x04 \x01(\x04R\fsourceHandle\")\n" +
	"\x13HashContentResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"K\n" +
	"\rReadAtRequest\x12\x10\n" +
	"\x03off\x18\x01 \x01(\x03R\x03off\x12\x10\n" +
	"\x03len\x18\x02 \x01(\x05R\x03len\x12\x16\n" +
	"\x06handle\x18\x03 \x01(\x04R\x06handle\"6\n" +
	"\x0eReadAtResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"\xbc\x01\n" +
	"\x05Error\x120\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1c.drivel.plugin.v1.Error.KindR\x04kind\x12\x1c\n" +
	"\tretryable\x18\x02 \x01(\bR\tretryable\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"I\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eKIND_NOT_EXIST\x10\x01\x12\x17\n" +
	"\x13KIND_CURSOR_EXPIRED\x10\x022\xb2\b\n" +
	"\bProvider\x12E\n" +
	"\x04Open\x12\x1d.drivel.plugin.v1.OpenRequest\x1a\x1e.drivel.plugin.v1.OpenResponse\x12H\n" +
	"\x05Close\x12\x1e.drivel.plugin.v1.CloseRequest\x1a\x1f.drivel.plugin.v1.CloseResponse\x12E\n" +
	"\x03Put\x12\x1c.drivel.plugin.v1.PutRequest\x1a\x1e.drivel.plugin.v1.FileResponse(\x01\x12G\n" +
	"\x05Mkdir\x12\x1e.drivel.plugin.v1.MkdirRequest\x1a\x1e.drivel.plugin.v1.FileResponse\x12E\n" +
	"\x04Move\x12\x1d.drivel.plugin.v1.MoveRequest\x1a\x1e.drivel.plugin.v1.FileResponse\x12K\n" +
	"\x06Remove\x12\x1f.drivel.plugin.v1.RemoveRequest\x1a .drivel.plugin.v1.RemoveResponse\x12>\n" +
	"\x03Get\x12\x1c.drivel.plugin.v1.GetRequest\x1a\x17.drivel.plugin.v1.Chunk0\x01\x12E\n" +
	"\x04Stat\x12\x1d.drivel.plugin.v1.StatRequest\x1a\x1e.drivel.plugin.v1.StatResponse\x12Z\n" +
	"\vStartCursor\x12$.drivel.plugin.v1.StartCursorRequest\x1a%.drivel.plugin.v1.StartCursorResponse\x12N\n" +
	"\aChanges\x12 .drivel.plugin.v1.ChangesRequest\x1a!.drivel.plugin.v1.ChangesResponse\x12T\n" +
	"\tEnumerate\x12\".drivel.plugin.v1.EnumerateRequest\x1a#.drivel.plugin.v1.EnumerateResponse\x12H\n" +
	"\bGetRange\x12!.drivel.plugin.v1.GetRangeRequest\x1a\x17.drivel.plugin.v1.Chunk0\x01\x12M\n" +
	"\bPutRange\x12!.drivel.plugin.v1.PutRangeRequest\x1a\x1e.drivel.plugin.v1.FileResponse\x12O\n" +
	"\vHashContent\x12\x17.drivel.plugin.v1.Chunk\x1a%.drivel.plugin.v1.HashContentResponse(\x012V\n" +
	"\aContent\x12K\n" +
	"\x06ReadAt\x12\x1f.drivel.plugin.v1.ReadAtRequest\x1a .drivel.plugin.v1.ReadAtResponseB3Z1github.com/zishmusic/drivel/plugin/internal/pb;pbb\x06proto3"

var (
	file_drivel_plugin_v1_provider_proto_rawDescOnce sync.Once
	file_drivel_plugin_v1_provider_proto_rawDescData []byte
)

func file_drivel_plugin_v1_provider_proto_rawDescGZIP() []byte {
	file_drivel_plugin_v1_provider_proto_rawDescOnce.Do(func() {
		file_drivel_plugin_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drivel_plugin_v1_provider_proto_rawDesc), len(file_drivel_plugin_v1_provider_proto_rawDesc)))
	})
	return file_drivel_plugin_v1_provider_proto_rawDescData
}

var file_drivel_plugin_v1_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_drivel_plugin_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_drivel_plugin_v1_provider_proto_goTypes = []any{
	(Error_Kind)(0),               // 0: drivel.plugin.v1.Error.Kind
	(*OpenRequest)(nil),           // 1: drivel.plugin.v1.OpenRequest
	(*OpenResponse)(nil),          // 2: drivel.plugin.v1.OpenResponse
	(*CloseRequest)(nil),          // 3: drivel.plugin.v1.CloseRequest
	(*CloseResponse)(nil),         // 4: drivel.plugin.v1.CloseResponse
	(*File)(nil),                  // 5: drivel.plugin.v1.File
	(*Change)(nil),                // 6: drivel.plugin.v1.Change
	(*Chunk)(nil),                 // 7: drivel.plugin.v1.Chunk
	(*PutRequest)(nil),            // 8: drivel.plugin.v1.PutRequest
	(*FileResponse)(nil),          // 9: drivel.plugin.v1.FileResponse
	(*MkdirRequest)(nil),          // 10: drivel.plugin.v1.MkdirRequest
	(*MoveRequest)(nil),           // 11: drivel.plugin.v1.MoveRequest
	(*RemoveRequest)(nil),         // 12: drivel.plugin.v1.RemoveRequest
	(*RemoveResponse)(nil),        // 13: drivel.plugin.v1.RemoveResponse
	(*GetRequest)(nil),            // 14: drivel.plugin.v1.GetRequest
	(*StatRequest)(nil),           // 15: drivel.plugin.v1.StatRequest
	(*StatResponse)(nil),          // 16: drivel.plugin.v1.StatResponse
	(*StartCursorRequest)(nil),    // 17: drivel.plugin.v1.StartCursorRequest
	(*StartCursorResponse)(nil),   // 18: drivel.plugin.v1.StartCursorResponse
	(*ChangesRequest)(nil),        // 19: drivel.plugin.v1.ChangesRequest
	(*ChangesResponse)(nil),       // 20: drivel.plugin.v1.ChangesResponse
	(*EnumerateRequest)(nil),      // 21: drivel.plugin.v1.EnumerateRequest
	(*EnumerateResponse)(nil),     // 22: drivel.plugin.v1.EnumerateResponse
	(*GetRangeRequest)(nil),       // 23: drivel.plugin.v1.GetRangeRequest
	(*Extent)(nil),                // 24: drivel.plugin.v1.Extent
	(*PutRangeRequest)(nil),       // 25: drivel.plugin.v1.PutRangeRequest
	(*HashContentResponse)(nil),   // 26: drivel.plugin.v1.HashContentResponse
	(*ReadAtRequest)(nil),         // 27: drivel.plugin.v1.ReadAtRequest
	(*ReadAtResponse)(nil),        // 28: drivel.plugin.v1.ReadAtResponse
	(*Error)(nil),                 // 29: drivel.plugin.v1.Error
	(*timestamppb.Timestamp)(nil), // 30: google.protobuf.Timestamp
}
var file_drivel_plugin_v1_provider_proto_depIdxs = []int32{
	30, // 0: drivel.plugin.v1.File.modified:type_name -> google.protobuf.Timestamp
	5,  // 1: drivel.plugin.v1.Change.file:type_name -> drivel.plugin.v1.File
	5,  // 2: drivel.plugin.v1.FileResponse.file:type_name -> drivel.plugin.v1.File
	5,  // 3: drivel.plugin.v1.StatResponse.file:type_name -> drivel.plugin.v1.File
	6,  // 4: drivel.plugin.v1.ChangesResponse.changes:type_name -> drivel.plugin.v1.Change
	5,  // 5: drivel.plugin.v1.EnumerateResponse.files:type_name -> drivel.plugin.v1.File
	24, // 6: drivel.plugin.v1.PutRangeRequest.extents:type_name -> drivel.plugin.v1.Extent
	0,  // 7: drivel.plugin.v1.Error.kind:type_name -> drivel.plugin.v1.Error.Kind
	1,  // 8: drivel.plugin.v1.Provider.Open:input_type -> drivel.plugin.v1.OpenRequest
	3,  // 9: drivel.plugin.v1.Provider.Close:input_type -> drivel.plugin.v1.CloseRequest
	8,  // 10: drivel.plugin.v1.Provider.Put:input_type -> drivel.plugin.v1.PutRequest
	10, // 11: drivel.plugin.v1.Provider.Mkdir:input_type -> drivel.plugin.v1.MkdirRequest
	11, // 12: drivel.plugin.v1.Provider.Move:input_type -> drivel.plugin.v1.MoveRequest
	12, // 13: drivel.plugin.v1.Provider.Remove:input_type -> drivel.plugin.v1.RemoveRequest
	14, // 14: drivel.plugin.v1.Provider.Get:input_type -> drivel.plugin.v1.GetRequest
	15, // 15: drivel.plugin.v1.Provider.Stat:input_type -> drivel.plugin.v1.StatRequest
	17, // 16: drivel.plugin.v1.Provider.StartCursor:input_type -> drivel.plugin.v1.StartCursorRequest
	19, // 17: drivel.plugin.v1.Provider.Changes:input_type -> drivel.plugin.v1.ChangesRequest
	21, // 18: drivel.plugin.v1.Provider.Enumerate:input_type -> drivel.plugin.v1.EnumerateRequest
	23, // 19: drivel.plugin.v1.Provider.GetRange:input_type -> drivel.plugin.v1.GetRangeRequest
	25, // 20: drivel.plugin.v1.Provider.PutRange:input_type -> drivel.plugin.v1.PutRangeRequest
	7,  // 21: drivel.plugin.v1.Provider.HashContent:input_type -> drivel.plugin.v1.Chunk
	27, // 22: drivel.plugin.v1.Content.ReadAt:input_type -> drivel.plugin.v1.ReadAtRequest
	2,  // 23: drivel.plugin.v1.Provider.Open:output_type -> drivel.plugin.v1.OpenResponse
	4,  // 24: drivel.plugin.v1.Provider.Close:output_type -> drivel.plugin.v1.CloseResponse
	9,  // 25: drivel.plugin.v1.Provider.Put:output_type -> drivel.plugin.v1.FileResponse
	9,  // 26: drivel.plugin.v1.Provider.Mkdir:output_type -> drivel.plugin.v1.FileResponse
	9,  // 27: drivel.plugin.v1.Provider.Move:output_type -> drivel.plugin.v1.FileResponse
	13, // 28: drivel.plugin.v1.Provider.Remove:output_type -> drivel.plugin.v1.RemoveResponse
	7,  // 29: drivel.plugin.v1.Provider.Get:output_type -> drivel.plugin.v1.Chunk
	16, // 30: drivel.plugin.v1.Provider.Stat:output_type -> drivel.plugin.v1.StatResponse
	18, // 31: drivel.plugin.v1.Provider.StartCursor:output_type -> drivel.plugin.v1.StartCursorResponse
	20, // 32: drivel.plugin.v1.Provider.Changes:output_type -> drivel.plugin.v1.ChangesResponse
	22, // 33: drivel.plugin.v1.Provider.Enumerate:output_type -> drivel.plugin.v1.EnumerateResponse
	7,  // 34: drivel.plugin.v1.Provider.GetRange:output_type -> drivel.plugin.v1.Chunk
	9,  // 35: drivel.plugin.v1.Provider.PutRange:output_type -> drivel.plugin.v1.FileResponse
	26, // 36: drivel.plugin.v1.Provider.HashContent:output_type -> drivel.plugin.v1.HashContentResponse
	28, // 37: drivel.plugin.v1.Content.ReadAt:output_type -> drivel.plugin.v1.ReadAtResponse
	23, // [23:38] is the sub-list for method output_type
	8,  // [8:23] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_drivel_plugin_v1_provider_proto_init() }
func file_drivel_plugin_v1_provider_proto_init() {
	if File_drivel_plugin_v1_provider_proto != nil {
		return
	}
	file_drivel_plugin_v1_provider_proto_msgTypes[7].OneofWrappers = []any{
		(*PutRequest_Path)(nil),
		(*PutRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drivel_plugin_v1_provider_proto_rawDesc), len(file_drivel_plugin_v1_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_drivel_plugin_v1_provider_proto_goTypes,
		DependencyIndexes: file_drivel_plugin_v1_provider_proto_depIdxs,
		EnumInfos:         file_drivel_plugin_v1_provider_proto_enumTypes,
		MessageInfos:      file_drivel_plugin_v1_provider_proto_msgTypes,
	}.Build()
	File_drivel_plugin_v1_provider_proto = out.File
	file_drivel_plugin_v1_provider_proto_goTypes = nil
	file_drivel_plugin_v1_provider_proto_depIdxs = nil
}
