// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
// SPDX-License-Identifier: MPL-2.0

// The drivel provider plugin protocol (M9).
//
// This file is the compatibility surface between a drivel host and a backend
// running in its own process. Everything in it mirrors a Go declaration in
// github.com/zishmusic/drivel/provider, and the mapping is deliberately dull:
// the seam was designed in M2 and proven in M8, and M9 is about the loading
// mechanism, not about redesigning the interface.
//
// Two rules govern changes here.
//
//   - Fields are added, never renumbered or reused. A host and a plugin are
//     separately built binaries that a user may upgrade independently, which is
//     the whole reason the protocol exists.
//   - A capability is named by a string, not by a field number. Which optional
//     interfaces a backend offers is answered once, at Open, because a gRPC stub
//     implements every method whether or not the backend behind it can honour
//     them — see provider.Capability for what goes wrong otherwise.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: drivel/plugin/v1/provider.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Provider_Open_FullMethodName        = "/drivel.plugin.v1.Provider/Open"
	Provider_Close_FullMethodName       = "/drivel.plugin.v1.Provider/Close"
	Provider_Put_FullMethodName         = "/drivel.plugin.v1.Provider/Put"
	Provider_Mkdir_FullMethodName       = "/drivel.plugin.v1.Provider/Mkdir"
	Provider_Move_FullMethodName        = "/drivel.plugin.v1.Provider/Move"
	Provider_Remove_FullMethodName      = "/drivel.plugin.v1.Provider/Remove"
	Provider_Get_FullMethodName         = "/drivel.plugin.v1.Provider/Get"
	Provider_Stat_FullMethodName        = "/drivel.plugin.v1.Provider/Stat"
	Provider_StartCursor_FullMethodName = "/drivel.plugin.v1.Provider/StartCursor"
	Provider_Changes_FullMethodName     = "/drivel.plugin.v1.Provider/Changes"
	Provider_Enumerate_FullMethodName   = "/drivel.plugin.v1.Provider/Enumerate"
	Provider_GetRange_FullMethodName    = "/drivel.plugin.v1.Provider/GetRange"
	Provider_PutRange_FullMethodName    = "/drivel.plugin.v1.Provider/PutRange"
	Provider_HashContent_FullMethodName = "/drivel.plugin.v1.Provider/HashContent"
)

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Provider is one backend, serving exactly one mount. A host launches one plugin
// process per mount rather than sharing one across a process's mounts: two
// mounts are two sets of credentials, and keeping them in separate processes is
// the same per-mount isolation rule that keeps their state DBs, engines and
// worker pools apart.
type ProviderClient interface {
	// Open hands the backend its configuration and asks what it can do. It is
	// called exactly once per process, before anything else.
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error)
	// Close releases the backend. The host calls it before killing the process, so
	// a backend holding a local database (Drive's path index) can commit and
	// unlock rather than being terminated mid-write.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	// provider.Store — the required surface.
	//
	// Put streams: the first message carries the path, every later message carries
	// content. Splitting it that way keeps the request under any message-size
	// limit for a file of any size, which a single bytes field would not.
	Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, FileResponse], error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*FileResponse, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*FileResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error)
	// provider.ChangeSource — optional.
	StartCursor(ctx context.Context, in *StartCursorRequest, opts ...grpc.CallOption) (*StartCursorResponse, error)
	Changes(ctx context.Context, in *ChangesRequest, opts ...grpc.CallOption) (*ChangesResponse, error)
	// provider.Enumerator — optional.
	Enumerate(ctx context.Context, in *EnumerateRequest, opts ...grpc.CallOption) (*EnumerateResponse, error)
	// provider.RangeGetter — optional.
	GetRange(ctx context.Context, in *GetRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	// provider.RangePutter — optional. The local file is NOT streamed into this
	// call: provider.RangePutter takes an io.ReaderAt precisely so that an
	// implementation may seek to its extents in whatever order its wire protocol
	// prefers, and a stream would take that back. The request names a handle
	// instead, which the plugin reads through the Content service the host
	// advertised at Open.
	PutRange(ctx context.Context, in *PutRangeRequest, opts ...grpc.CallOption) (*FileResponse, error)
	// provider.ContentHasher — optional. Streamed for the same reason Put is.
	HashContent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, HashContentResponse], error)
}

type providerClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderClient(cc grpc.ClientConnInterface) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenResponse)
	err := c.cc.Invoke(ctx, Provider_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, Provider_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Put(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutRequest, FileResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[0], Provider_Put_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutRequest, FileResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_PutClient = grpc.ClientStreamingClient[PutRequest, FileResponse]

func (c *providerClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, Provider_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, Provider_Move_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, Provider_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[1], Provider_Get_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_GetClient = grpc.ServerStreamingClient[Chunk]

func (c *providerClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatResponse)
	err := c.cc.Invoke(ctx, Provider_Stat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) StartCursor(ctx context.Context, in *StartCursorRequest, opts ...grpc.CallOption) (*StartCursorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartCursorResponse)
	err := c.cc.Invoke(ctx, Provider_StartCursor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Changes(ctx context.Context, in *ChangesRequest, opts ...grpc.CallOption) (*ChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangesResponse)
	err := c.cc.Invoke(ctx, Provider_Changes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Enumerate(ctx context.Context, in *EnumerateRequest, opts ...grpc.CallOption) (*EnumerateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumerateResponse)
	err := c.cc.Invoke(ctx, Provider_Enumerate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) GetRange(ctx context.Context, in *GetRangeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[2], Provider_GetRange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetRangeRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_GetRangeClient = grpc.ServerStreamingClient[Chunk]

func (c *providerClient) PutRange(ctx context.Context, in *PutRangeRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, Provider_PutRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) HashContent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, HashContentResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Provider_ServiceDesc.Streams[3], Provider_HashContent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, HashContentResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_HashContentClient = grpc.ClientStreamingClient[Chunk, HashContentResponse]

// ProviderServer is the server API for Provider service.
// All implementations must embed UnimplementedProviderServer
// for forward compatibility.
//
// Provider is one backend, serving exactly one mount. A host launches one plugin
// process per mount rather than sharing one across a process's mounts: two
// mounts are two sets of credentials, and keeping them in separate processes is
// the same per-mount isolation rule that keeps their state DBs, engines and
// worker pools apart.
type ProviderServer interface {
	// Open hands the backend its configuration and asks what it can do. It is
	// called exactly once per process, before anything else.
	Open(context.Context, *OpenRequest) (*OpenResponse, error)
	// Close releases the backend. The host calls it before killing the process, so
	// a backend holding a local database (Drive's path index) can commit and
	// unlock rather than being terminated mid-write.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	// provider.Store — the required surface.
	//
	// Put streams: the first message carries the path, every later message carries
	// content. Splitting it that way keeps the request under any message-size
	// limit for a file of any size, which a single bytes field would not.
	Put(grpc.ClientStreamingServer[PutRequest, FileResponse]) error
	Mkdir(context.Context, *MkdirRequest) (*FileResponse, error)
	Move(context.Context, *MoveRequest) (*FileResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	Get(*GetRequest, grpc.ServerStreamingServer[Chunk]) error
	Stat(context.Context, *StatRequest) (*StatResponse, error)
	// provider.ChangeSource — optional.
	StartCursor(context.Context, *StartCursorRequest) (*StartCursorResponse, error)
	Changes(context.Context, *ChangesRequest) (*ChangesResponse, error)
	// provider.Enumerator — optional.
	Enumerate(context.Context, *EnumerateRequest) (*EnumerateResponse, error)
	// provider.RangeGetter — optional.
	GetRange(*GetRangeRequest, grpc.ServerStreamingServer[Chunk]) error
	// provider.RangePutter — optional. The local file is NOT streamed into this
	// call: provider.RangePutter takes an io.ReaderAt precisely so that an
	// implementation may seek to its extents in whatever order its wire protocol
	// prefers, and a stream would take that back. The request names a handle
	// instead, which the plugin reads through the Content service the host
	// advertised at Open.
	PutRange(context.Context, *PutRangeRequest) (*FileResponse, error)
	// provider.ContentHasher — optional. Streamed for the same reason Put is.
	HashContent(grpc.ClientStreamingServer[Chunk, HashContentResponse]) error
	mustEmbedUnimplementedProviderServer()
}

// UnimplementedProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderServer struct{}

func (UnimplementedProviderServer) Open(context.Context, *OpenRequest) (*OpenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedProviderServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedProviderServer) Put(grpc.ClientStreamingServer[PutRequest, FileResponse]) error {
	return status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedProviderServer) Mkdir(context.Context, *MkdirRequest) (*FileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedProviderServer) Move(context.Context, *MoveRequest) (*FileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Move not implemented")
}
func (UnimplementedProviderServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedProviderServer) Get(*GetRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedProviderServer) Stat(context.Context, *StatRequest) (*StatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedProviderServer) StartCursor(context.Context, *StartCursorRequest) (*StartCursorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartCursor not implemented")
}
func (UnimplementedProviderServer) Changes(context.Context, *ChangesRequest) (*ChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Changes not implemented")
}
func (UnimplementedProviderServer) Enumerate(context.Context, *EnumerateRequest) (*EnumerateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enumerate not implemented")
}
func (UnimplementedProviderServer) GetRange(*GetRangeRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Error(codes.Unimplemented, "method GetRange not implemented")
}
func (UnimplementedProviderServer) PutRange(context.Context, *PutRangeRequest) (*FileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutRange not implemented")
}
func (UnimplementedProviderServer) HashContent(grpc.ClientStreamingServer[Chunk, HashContentResponse]) error {
	return status.Error(codes.Unimplemented, "method HashContent not implemented")
}
func (UnimplementedProviderServer) mustEmbedUnimplementedProviderServer() {}
func (UnimplementedProviderServer) testEmbeddedByValue()                  {}

// UnsafeProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderServer will
// result in compilation errors.
type UnsafeProviderServer interface {
	mustEmbedUnimplementedProviderServer()
}

func RegisterProviderServer(s grpc.ServiceRegistrar, srv ProviderServer) {
	// If the following call panics, it indicates UnimplementedProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Provider_ServiceDesc, srv)
}

func _Provider_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServer).Put(&grpc.GenericServerStream[PutRequest, FileResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_PutServer = grpc.ClientStreamingServer[PutRequest, FileResponse]

func _Provider_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Move_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Get_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServer).Get(m, &grpc.GenericServerStream[GetRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_GetServer = grpc.ServerStreamingServer[Chunk]

func _Provider_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Stat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_StartCursor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCursorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).StartCursor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_StartCursor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).StartCursor(ctx, req.(*StartCursorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Changes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Changes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Changes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Changes(ctx, req.(*ChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Enumerate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Enumerate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_Enumerate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Enumerate(ctx, req.(*EnumerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_GetRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProviderServer).GetRange(m, &grpc.GenericServerStream[GetRangeRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_GetRangeServer = grpc.ServerStreamingServer[Chunk]

func _Provider_PutRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).PutRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Provider_PutRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).PutRange(ctx, req.(*PutRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_HashContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProviderServer).HashContent(&grpc.GenericServerStream[Chunk, HashContentResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Provider_HashContentServer = grpc.ClientStreamingServer[Chunk, HashContentResponse]

// Provider_ServiceDesc is the grpc.ServiceDesc for Provider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Provider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drivel.plugin.v1.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _Provider_Open_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _Provider_Close_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _Provider_Mkdir_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _Provider_Move_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Provider_Remove_Handler,
		},
		{
			MethodName: "Stat",
			Handler:    _Provider_Stat_Handler,
		},
		{
			MethodName: "StartCursor",
			Handler:    _Provider_StartCursor_Handler,
		},
		{
			MethodName: "Changes",
			Handler:    _Provider_Changes_Handler,
		},
		{
			MethodName: "Enumerate",
			Handler:    _Provider_Enumerate_Handler,
		},
		{
			MethodName: "PutRange",
			Handler:    _Provider_PutRange_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _Provider_Put_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Get",
			Handler:       _Provider_Get_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetRange",
			Handler:       _Provider_GetRange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HashContent",
			Handler:       _Provider_HashContent_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "drivel/plugin/v1/provider.proto",
}

const (
	Content_ReadAt_FullMethodName = "/drivel.plugin.v1.Content/ReadAt"
)

// ContentClient is the client API for Content service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Content is served by the HOST and called by the plugin: random access to a
// local file the plugin has been asked to patch. It is the only call that runs
// in that direction, and it is deliberately the narrowest thing that satisfies
// io.ReaderAt — a plugin cannot ask for a path, only for bytes of the file the
// host already decided to send it.
type ContentClient interface {
	ReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (*ReadAtResponse, error)
}

type contentClient struct {
	cc grpc.ClientConnInterface
}

func NewContentClient(cc grpc.ClientConnInterface) ContentClient {
	return &contentClient{cc}
}

func (c *contentClient) ReadAt(ctx context.Context, in *ReadAtRequest, opts ...grpc.CallOption) (*ReadAtResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAtResponse)
	err := c.cc.Invoke(ctx, Content_ReadAt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContentServer is the server API for Content service.
// All implementations must embed UnimplementedContentServer
// for forward compatibility.
//
// Content is served by the HOST and called by the plugin: random access to a
// local file the plugin has been asked to patch. It is the only call that runs
// in that direction, and it is deliberately the narrowest thing that satisfies
// io.ReaderAt — a plugin cannot ask for a path, only for bytes of the file the
// host already decided to send it.
type ContentServer interface {
	ReadAt(context.Context, *ReadAtRequest) (*ReadAtResponse, error)
	mustEmbedUnimplementedContentServer()
}

// UnimplementedContentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContentServer struct{}

func (UnimplementedContentServer) ReadAt(context.Context, *ReadAtRequest) (*ReadAtResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadAt not implemented")
}
func (UnimplementedContentServer) mustEmbedUnimplementedContentServer() {}
func (UnimplementedContentServer) testEmbeddedByValue()                 {}

// UnsafeContentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContentServer will
// result in compilation errors.
type UnsafeContentServer interface {
	mustEmbedUnimplementedContentServer()
}

func RegisterContentServer(s grpc.ServiceRegistrar, srv ContentServer) {
	// If the following call panics, it indicates UnimplementedContentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Content_ServiceDesc, srv)
}

func _Content_ReadAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentServer).ReadAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Content_ReadAt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentServer).ReadAt(ctx, req.(*ReadAtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Content_ServiceDesc is the grpc.ServiceDesc for Content service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Content_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drivel.plugin.v1.Content",
	HandlerType: (*ContentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAt",
			Handler:    _Content_ReadAt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drivel/plugin/v1/provider.proto",
}
