# bash completion for drivel                               -*- shell-script -*-
#
# GENERATED by `make completions` from the flag definitions in cmd/drivel.
# Do not edit: add the flag, give it a completion hint, and regenerate.
#
# Install:
#   # system-wide (Debian/Ubuntu/Fedora):
#   sudo cp completions/drivel.bash /usr/share/bash-completion/completions/drivel
#   # or per-user, sourced from ~/.bashrc:
#   source /path/to/drivel/completions/drivel.bash
#
# Requires the bash-completion package for the _init_completion helper; a
# minimal fallback is used when it is absent.

_drivel() {
    local cur prev words cword
    if declare -F _init_completion >/dev/null 2>&1; then
        _init_completion -n : || return
    else
        # Minimal fallback when bash-completion isn't loaded.
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
        words=("${COMP_WORDS[@]}")
        cword=$COMP_CWORD
    fi

    local subcommands="login mount help"

    # Determine the active subcommand (first non-flag word after the program).
    local sub="" i
    for (( i=1; i < cword; i++ )); do
        case "${words[i]}" in
            -*) ;;
            *) sub="${words[i]}"; break ;;
        esac
    done
    # A leading flag (e.g. `drivel -config ...`) implies the default command.
    if [[ -z $sub && ${words[1]} == -* ]]; then
        sub="mount"
    fi

    # Value completion, decided by the flag before the cursor.
    case "$prev" in
        -data|-mount)
            _filedir -d
            return
            ;;
        -config|-credentials|-index|-state|-token)
            _filedir
            return
            ;;
        -drive-delete)
            COMPREPLY=( $(compgen -W "trash permanent" -- "$cur") )
            return
            ;;
        -drive-sweep-mode)
            COMPREPLY=( $(compgen -W "auto flat scoped" -- "$cur") )
            return
            ;;
        -scope)
            COMPREPLY=( $(compgen -W "drive drive.readonly drive.file" -- "$cur") )
            return
            ;;
        -account|-client-id|-client-secret|-drive-root|-hydrate-workers|-max-deletes|-port|-pprof|-project-id|-sweep-interval|-upload-workers)
            # Values nothing can suggest: an ID, a port, a duration.
            return
            ;;
    esac

    # The command slot: a subcommand, or the default command's flags.
    if [[ -z $sub ]]; then
        if [[ $cur == -* ]]; then
            COMPREPLY=( $(compgen -W "-config -credentials -data -debug -drive-delete -drive-root -drive-sweep-mode -hydrate-workers -index -lazy -materialize -max-deletes -mount -pprof -pprof-allow-remote -resync -state -sweep-interval -token -upload-workers -xattr -h -help" -- "$cur") )
        else
            COMPREPLY=( $(compgen -W "$subcommands" -- "$cur") )
        fi
        return
    fi

    # Flag completion within a subcommand.
    local flags=""
    case "$sub" in
        login) flags="-account -client-id -client-secret -config -credentials -open -port -project-id -scope -token -h -help" ;;
        mount) flags="-config -credentials -data -debug -drive-delete -drive-root -drive-sweep-mode -hydrate-workers -index -lazy -materialize -max-deletes -mount -pprof -pprof-allow-remote -resync -state -sweep-interval -token -upload-workers -xattr -h -help" ;;
        help) return ;;
    esac
    if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$flags" -- "$cur") )
    fi
}

complete -F _drivel drivel
